apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-10-13T21:45:18Z"
  generation: 1
  labels:
    app: digitreader
  name: digitreader
  namespace: default
  resourceVersion: "976"
  uid: a9ea3929-63d0-40b3-8d2a-29165a94559a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: digitreader
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: digitreader
    spec:
      containers:
      - image: tuanhmt/digitreader:v1.0
        imagePullPolicy: Never
        name: digitreader
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
